Fix#240/add build step to construct psm1
PowerShell/PowerShellGetv2 pull request #242
Opened 2018-03-10 11:55 UTC by Benny1007

2018-03-10 12:00 UTC, Benny1007 commented
Code to merge public and private functions into one psm1 file to address https://github.com/PowerShell/PowerShellGet/issues/240

2018-03-12 19:08 UTC, bmanikm commented on tools/build.psm1
> +    Update-ModuleManifest -Path "$ModuleRoot\PowerShellGet.psd1" -FunctionsToExport $PublicFunctions.BaseName
>$PublicFunctions.BaseName [](start = 84, length = 25)

This adds all the provider level public functions at module level.

2018-03-12 19:12 UTC, bmanikm commented on Tests/PSGetPublishScript.Tests.ps1
> +    # this test is skipped for now as it is failing due to the /public/Install-Package.ps1 not taking a -Name parameter.
>this test is skipped for now as it is failing due to the /public/Install-Package.ps1 not taking a -Name parameter. [](start = 6, length = 114)

It is not clear why this test needs to be skipped. Install-Package is a provider level public function and implements the PackageManagement provider level Install-Package functionality.

2018-03-12 19:24 UTC, bmanikm commented on tools/build.psm1
> +}
Can we avoid the in-place update of the module contents? like having a <root>\bin\PowerShellGet folder then copying this folder to the AllUsers scope during the test runs?

2018-03-12 19:28 UTC, bmanikm commented
Please take a look at the CI test failures.

---
In reply to: [372024549](https://github.com/PowerShell/PowerShellGet/pull/242#issuecomment-372024549) [](ancestors = 372024549)

2018-03-12 19:28 UTC, bmanikm requested changes
:clock1:

2018-03-12 23:32 UTC, Benny1007 commented
Thanks for that, are you saying there are affectively two modules here defined in the one module file? And that the ExportModuleMember -Functions in the PSM file list is actually different to the FunctionsToExport list in the PSM1. This seems odd to me.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Manikyam Bavandla <notifications@github.com>
Sent: Tuesday, March 13, 2018 3:08:44 AM
To: PowerShell/PowerShellGet
Cc: benny1007; Author
Subject: Re: [PowerShell/PowerShellGet] Fix#240/add build step to construct psm1 (#242)


@bmanikm commented on this pull request.

________________________________

In tools/build.psm1<https://github.com/PowerShell/PowerShellGet/pull/242#discussion_r173913578>:

> +        $publicFunctionsString += "$PublicFunction,"
+    }
+
+    $publicFunctionsString = $publicFunctionsString.TrimEnd(",")
+    $FunctionExportString = "Export-ModuleMember -Function $publicFunctionsString"
+
+    $ModuleFileContent = Get-Content -Path $ModuleFile
+    $ModuleFileContent = $ModuleFileContent.Replace("#buildScriptPrivateFunctionsGoHere", $PrivateFunctionContent)
+    $ModuleFileContent = $ModuleFileContent.Replace("#buildScriptPublicFunctionsGoHere", $PublicFunctionContent)
+    $ModuleFileContent = $ModuleFileContent.Replace("#buildScriptExportFunctionsGoHere", $FunctionExportString)
+
+    Write-Verbose -Message "Writing functions to PSM1 file"
+    Set-Content -Path $ModuleFile -Value $ModuleFileContent
+
+    Write-Verbose -Message "Updating module manifest file"
+    Update-ModuleManifest -Path "$ModuleRoot\PowerShellGet.psd1" -FunctionsToExport $PublicFunctions.BaseName


$PublicFunctions.BaseName [](start = 84, length = 25)

This adds all the provider level public functions at module level.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/PowerShell/PowerShellGet/pull/242#pullrequestreview-103181269>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AexDYd9AqbtarCaLrKYs_gxii8qblXTCks5tdse8gaJpZM4SlP_l>.

2018-03-13 10:28 UTC, Benny1007 commented on tools/build.psm1
> +}
It's not really in place as it happens before any tests have been kicked off, this is what the tests should be run against (a compiled psm1 file). I don't think it should be a responsibility of the tests to rearrange or package up the artifact into it's final form the Invoke-PowerShellGetTest already seems to be doing too much, and more than just tests.

2018-03-13 10:30 UTC, Benny1007 commented on Tests/PSGetPublishScript.Tests.ps1
> +    # this test is skipped for now as it is failing due to the /public/Install-Package.ps1 not taking a -Name parameter.
..but the script under test was passing a -Name parameter, something Install-Package does not have? I can reintroduce this, but I am getting different test failures with each build that are unrelated to this latest PR I think.

2018-03-13 18:54 UTC, bmanikm commented on tools/build.psm1
> +}
build.psm1 files can be used on our development machines, in that case all the local changes in the individual files will be lost due to this removal step.

2018-03-13 19:20 UTC, bmanikm commented
@Benny1007 Please take a look at the below topics for more details. 
[How does PackageManagement relate to PowerShellGet? (High Level Answer)](https://docs.microsoft.com/en-us/powershell/gallery/psgallery/psgallery_faqs#how-does-packagemanagement-relate-to-powershellget-high-level-answer)
[How does PackageManagement actually relate to PowerShellGet? (Technical Details)](
https://docs.microsoft.com/en-us/powershell/gallery/psgallery/psgallery_faqs#how-does-packagemanagement-actually-relate-to-powershellget-technical-details)

The PackageManagement provider functions, implemented in the PowerShellGet module, can't be used directly by the end-users, they can only be used with the PackageManagement cmdlets. That's they are not listed in the FunctionsToExport entry of the PowerShellGet module manifest.

All the public functions under public folder need to be separated into two folders, so that it will be easier to get the list of public cmdlets to be exported at the module level and the list of provider functions to be exported at provider level.

```
public\cmdlets
public\provider
```
(I am fine with other suitable names for the above proposed sub folders)

All public functions from both folders need to be listed as the Export-ModuleMember in PSModule.psm1 file.
All public functions under public\cmdlets dir need to be be listed as the FunctionsToExport in PowerShellGet.psd1 file.

2018-03-13 19:23 UTC, bmanikm commented on Tests/PSGetPublishScript.Tests.ps1
> +    # this test is skipped for now as it is failing due to the /public/Install-Package.ps1 not taking a -Name parameter.
Install-Package is a PackageManagement cmdlet. For more details, please take a look at https://github.com/PowerShell/PowerShellGet/pull/242#issuecomment-372787390.

2018-03-13 21:14 UTC, bmanikm commented
> # Create install locations for scripts if they are not already created

Please move below region placeholders prior to this. This is the reason for below error in CI test runs related to Test-RunningAsElevated usage.


```powershell
Test-RunningAsElevated : The term 'Test-RunningAsElevated' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\powershellcore\Modules\powershellget\1.6.2\PSModule.psm1:856 char:110
+ ... :ProgramFilesInstalledScriptInfosPath) -and (Test-RunningAsElevated))
+                                                  ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Test-RunningAsElevated:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```


```powershell
#region private functions imported via build script

#buildScriptPrivateFunctionsGoHere

#endregion

#region public functions imported via build script

#buildScriptPublicFunctionsGoHere

#endregion
```

---
Refers to: PowerShellGet/PSModule.psm1:855 in 84e1c78. [](commit_id = 84e1c78b60cbb1be40f0d892fa65be077517cd2d, deletion_comment = False)

2018-03-14 00:48 UTC, Benny1007 commented on tools/build.psm1
> +}
build.psm1 is just a script module tho?, loading it won't execute the function Remove-FunctionFolders. It will just load it into memory. The function is executed specifically by the Travis, and Appveyor config.

2018-03-14 00:54 UTC, Benny1007 commented
with regard to moving the regions for the function import, I will do this. (this was actually the reason I made it place holder replacement rather than just appending to the file, however I forgot the reason I did that.

2018-03-14 00:59 UTC, Benny1007 commented
I am still not clear about those explanations around Packagemangement vs PowerShellGet. From reading those pages it would seem that PowerShellGet is just a package manager, and PackageManagement is a common interface to work with ANY package manager so why are there Packagemanagement implementation details within the PowerShellGet? Shouldn't Packagemanagement be a separate repo, or is it a separate repo already and these functions are just used by packagemanagement?

2018-03-14 01:06 UTC, bmanikm commented on tools/build.psm1
> +}
To reproduce the CI failures, some times we will have to use the Merge-FunctionsIntoPSMFile and Remove-FunctionFolders functions from the build.psm1 on our dev machines, in that case we will loose the local uncommitted changes, if any, right?

2018-03-14 01:29 UTC, bmanikm commented
While merging the contents of individual files into the PSModule.psm1 file, we need to remove the below region, right?

```powershell
#region Load of module functions after split from main .psm1 file issue Fix#37

$PublicFunctions = @( Get-ChildItem -Path $PSScriptRoot\public\*.ps1 -ErrorAction SilentlyContinue )
$PrivateFunctions = @( Get-ChildItem -Path $PSScriptRoot\private\*.ps1 -ErrorAction SilentlyContinue )

# Load the separate function files from the private and public folders.
$AllFunctions = $PublicFunctions + $PrivateFunctions
foreach($function in $AllFunctions) {
    try {
        . $function.Fullname
    }
    catch {
        Write-Error -Message "Failed to import function $($function.fullname): $_"
    }
}

#endregion
```
Proposal:
- We might have to split the current contents of PSModule.psm1 file into multiple .ps1 files under PowerShellGet\private\init\ folder and dot source them in the PSModule.psm1 file. The current contents of PSModule.psm1 can be moved into `begin.ps1`, `process.ps1` and `end.ps1` files (these are just placeholder file names, I am open to other suitable names). 
- Move the private folder contents into private\functions\.
- `process.ps1` will be ignored during the single file construction. This file will have the dot source logic as in above region with some additional logic.
- During the single file construction, PSModule.psm1 file will be overwritten in Merge-FunctionsIntoPSMFile function.

2018-03-14 20:08 UTC, bmanikm commented on PowerShellGet/public/psmexports/Get-PSRepository.ps1
> +    .ExternalHelp PSModule-help.xml
>.ExternalHelp PSModule-help.xml [](start = 4, length = 31)

Get-PSRepository is a psd1 export function, please move this to public/psdexports folder.

2018-03-14 20:17 UTC, bmanikm commented on tools/build.psm1
> +    $psmFunctionExportString = "Export-ModuleMember -Function $psmExportFunctionNames"
This should also include the $PublicPSDFunctions.BaseName, otherwise no PublicPSDFunctions names will be exported at module level. This is the reason for CI test failures too.

2018-03-14 20:34 UTC, bmanikm commented
*Why are there Packagemanagement implementation details within the PowerShellGet? Shouldn't Packagemanagement be a separate repo, or is it a separate repo already and these functions are just used by packagemanagement?*

PackageManagement has its own repo --> https://github.com/oneget/oneget 
PowerShellGet is PackageManagement provider, so all the provider functions need to be implemented in this module, these provider functions can only be used with the PackageManagement cmdlets.

PackageManagment architecture can be found at https://github.com/oneget/oneget#get-started .

#### High-level execution flow of a PowerShellGet cmdlet
PowerShellGet\Install-Module --> PackageManagement\Install-Package --> PowerShellGet provider Install-Package function

2018-03-15 00:29 UTC, bmanikm commented on tools/build.psm1
> +    Update-ModuleManifest -Path "$ModuleRoot\PowerShellGet.psd1" -FunctionsToExport $PublicPSGetFunctions.BaseName
>Update-ModuleManifest -Path "$ModuleRoot\PowerShellGet.psd1" -FunctionsToExport $PublicPSGetFunctions.BaseName [](start = 4, length = 110)

This cmdlet is not available on PS v4, this impacts the AppVeyor test run on PS v4.

2018-03-15 00:41 UTC, bmanikm commented
@Benny1007 It looks like providerfunctions folder has psget function files and vice-versa.
Also please ensure that Get-PSRepository.ps1 file is under public\psgetfunctions folder as it is a PowerShellGet module level cmdlet.

2018-03-15 18:36 UTC, bmanikm commented on tools/build.psm1
> +        $ManifestFunctionExportString = "FunctionsToExport = @($($PublicPSGetFunctions.BaseName -Join ","))"
>$ManifestFunctionExportString = "FunctionsToExport = @($($PublicPSGetFunctions.BaseName -Join ","))" [](start = 8, length = 100)

Quotes are missing around each function name listed in the string. CI test run for PS 4 is blocked due to this issue.

Please change this line to below.

$ManifestFunctionExportString = "FunctionsToExport = @('$($PublicPSGetFunctions.BaseName -Join "', '")')"

2018-03-19 19:31 UTC, bmanikm commented on tools/build.psm1
> +}
This additional function can be avoided when the merged files are created under different path like bin\PowerShellGet. Please let me know your thoughts on why you prefer this additional Restore-PreMergedModuleFiles function.

With this function, during the development, we need to run two functions one for merging and other for restoring the changes prior to submitting the PR, right?

I prefer the merged files location to be bin\PowerShellGet (or some other path) instead of in-place merge.

2018-03-20 00:00 UTC, Benny1007 commented on tools/build.psm1
> +}
Yeah, it's a bit strange as I have split the repo out without ever having done any development on it. How do you envisage the development workflow?
For example if you were to work on the function Update-ModuleManifest how do you go about loading it, with all it's dependencies (throwerror in private functions) and in module scope? How do you step through debug the function? 
How do you see this working with the amalgamated psm1 file, the developer would have to do that merge in order to load the module and do debugging right? So the psm1 merge wouldn't just be performed in the build function.

apologies for the delay, but I am in gmt+8 timezone.

2018-03-20 02:50 UTC, bmanikm commented on tools/build.psm1
> +}
No worries @Benny1007, here are my thoughts:
- Split the current contents of `PSModule.psm1` file into two .ps1 files under `PowerShellGet\private\init\` folder.
- Move the current contents of PSModule.psm1 into `begin.ps1` and `end.ps1` files (these are just placeholder file names, I am open to suitable names).
- `begin.ps1` contents
  - Current contents of PSModule.psm1 above (in this PR) `#region private functions imported via build script`
 - `end.ps1` contents are 
   - Alias related code, and
   - Scripts folder creation code
 - Move the current files under `PowerShellGet\private\` folder into `PowerShellGet\private\functions\`.

- New code in PSModule.psm1
  - dot source logic in below order (NOTE: this will ensure that it is not required to create the merged file during the development)
    - `begin.ps1`
    - script files under `PowerShellGet\private\functions\`
    - script files under `PowerShellGet\public\psgetfunctions` and `PowerShellGet\private\providerfunctions`
    - `end.ps1`
  - There won't be any placeholders for creating the single .psm1 during CI runs.
  - Developer will have to add the PowerShellGet clone path at the beginning of the $env:PSModulePath, so that this path gets preference in loading the module and provider. Please note that during the development workflow, it is not required to execute the Merge-FunctionsIntoPSMFile function.
- Single file construction logic in Merge-FunctionsIntoPSMFile function during CI test runs and release time
  - Creates root\bin\PowerShellGet folder and deletes this folder contents, if there are any files from the previous merge run.
  - Copies the contents of root\PowerShellGet to root\bin\PowerShellGet folder.
  - Constructs the PSModule.psm1 file under root\bin\PowerShellGet
    - The current contents of PSModule.psm1 file will be overwritten.
    - Adds file content in the following order
      - `begin.ps1`
      - script files under `PowerShellGet\private\functions\`
      - script files under `PowerShellGet\public\psgetfunctions` and `PowerShellGet\public\providerfunctions`
      - Export-ModuleManifest line with all public function names under `PowerShellGet\public` folder.
      - `end.ps1`
    - Update-ModuleManifest logic for updating the FunctionsToExport entry.
- As part of the CI test runs, we need to copy the contents of root\bin\PowerShellGet folder instead of root\PowerShellGet folder.

2018-03-21 05:02 UTC, Benny1007 commented on tools/build.psm1
> +}
Yep that works. standby...

2018-03-25 02:56 UTC, bmanikm commented on PowerShellGet/private/modulefile/PartOne.ps1
> +
Is this change work fine with the merged singl psm1 file?

2018-03-25 03:04 UTC, bmanikm commented on tools/build.psm1
> +    Copy-Item -Path $ModuleRoot -Destination $ArtifactRoot -Recurse
It looks like the CI test runs are not validating the module created under dist/PowerShellGet, right? It is required to generate the dist/PowerShellGet folder and then copy it to the expected location in Invoke-PowerShellGetTest. Please take a look at the code starting at line # 310 or `# Copy OneGet and PSGet modules to PSHOME`

2018-03-25 10:36 UTC, Benny1007 commented on PowerShellGet/private/modulefile/PartOne.ps1
> +
This change was necessary to load the combined psm1 file with import-module. Without the -BaseDirectory switch the module would not load.

2018-03-25 10:39 UTC, Benny1007 commented on tools/build.psm1
> +    Copy-Item -Path $ModuleRoot -Destination $ArtifactRoot -Recurse
Are you saying you want the Invoke-PowerShellGetTest to do more than just run tests on the /private and /public structure but to actually assemble the distributed module and install it, then perform all tests on that /dist module? How would that work for local dev testing?

2018-03-26 01:49 UTC, bmanikm commented on PowerShellGet/private/modulefile/PartOne.ps1
> +
@Benny1007 This change is not working for the merged file scenario. I am getting below error as $baseDirctory assignment assumes the current folder structure `PowerShellGet/private/modulefile/`, right? To resolve this, we might have to move these partOne.ps1 and partTwo.ps1 files to the PowerShellGet folder and delete them during merge time.

```powershell
C:\>Import-Module PowerShellGet -Verbose -Force

Microsoft.PowerShell.Utility\Import-LocalizedData : Cannot find the Windows PowerShell data file 'PSGet.Resource.psd1' in directory 'C:\Program Files\WindowsPowerShell\Modules\en-US\', or in any parent culture
directories.
At C:\Program Files\WindowsPowerShell\Modules\powershellget\1.6.4\PSModule.psm1:465 char:1
+ Microsoft.PowerShell.Utility\Import-LocalizedData LocalizedData -file ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...t.Resource.psd1:String) [Import-LocalizedData], PSInvalidOperationException
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData
```

2018-03-26 02:05 UTC, bmanikm commented on tools/build.psm1
> +    Copy-Item -Path $ModuleRoot -Destination $ArtifactRoot -Recurse
@Benny1007 CI test runs should validate the generated module under /dist, right? otherwise, we are not sure /dist module is working fine or not. One such example is above mentioned Import-LocalizedData error.

I think, we need to move some portion of the Invoke-PowerShellGetTest function to a new function and handle additional logic for copying the generated PowerShellGet module /dist during CI test runs. During local dev testing, I am fine with executing the tests on /PowerShellGet folder instead of /dist/PowerShellGet folder.

2018-03-26 11:21 UTC, Benny1007 commented on PowerShellGet/private/modulefile/PartOne.ps1
> +
The module file PSModule.psm1 would not dot source the part one file, due to the -filename parameter of Import-LocalizedData assuming the local directory as it's source. At which point I added the -BaseDirectory parameter, and the $baseDirectory variable at line 464. At that point the module loaded fine.

M:\dev\repos\PowerShellGet\powershellget [fix#240/Add-build-step-to-construct-psm1 ↑2 +0 ~1 -0 ~]> Import-Module .\PSModule.psm1
WARNING: The names of some imported commands from the module 'PSModule' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
M:\dev\repos\PowerShellGet\powershellget [fix#240/Add-build-step-to-construct-psm1 ↑2 +0 ~1 -0 ~]>

Moving the partone and parttwo files seems a bit drastic, if the above isn't working could we not just use line 465 into the PSModule.psm1 before the dot sourcing of partone and remove the basedirectory parameter?

2018-03-26 11:44 UTC, Benny1007 commented on tools/build.psm1
> +    Copy-Item -Path $ModuleRoot -Destination $ArtifactRoot -Recurse
so something like this appveyor flow:-

install:
    Import-Module .\tools\build.psm1
    Install-Dependencies
    Update-ModuleManifestFunctions

test_script
    Publish-ModuleArtifacts
    Install-PublishedModule
    Invoke-PowerShellGetTest


on_finish
	New-ModuleArtifactZip


Now that the install of the module would be outside of the testing (a good thing imo) we would need to update the developer docs on the flow around importing the module locally before running the tests etc?

2018-03-26 23:47 UTC, bmanikm commented on tools/build.psm1
> +$script:ArtifactRoot = if($script:IsWindows) { "$ProjectRoot\dist" } else { "$ProjectRoot/dist" }
>if($script:IsWindows) { "$ProjectRoot\dist" } else { "$ProjectRoot/dist" } [](start = 23, length = 74)

Please consider using Join-Path cmdlet here so that this if-else logic is not required. Also consider this at other places too.

2018-03-27 00:02 UTC, bmanikm commented on tools/build.psm1
> +    Copy-Item -Path $ModuleRoot -Destination $ArtifactRoot -Recurse
Appveyor flow looks good to me. 
Yes, for running the tests locally, we need to update the documentation in [running-tests](https://github.com/PowerShell/PowerShellGet#running-tests) to prefix the clone path to $env:PSModulePath so that PowerShellGet will be loaded from the clone path.
`$env:PSModulePath = "$ClonePath;$env:PSModulePath"`

2018-03-27 00:08 UTC, bmanikm commented on PowerShellGet/private/modulefile/PartOne.ps1
> +
Above solution works for the developer scenario. When and where are you planning to add
`Microsoft.PowerShell.Utility\Import-LocalizedData LocalizedData -filename PSGet.Resource.psd1` line for the CI or merged file scenario?

2018-03-27 21:36 UTC, bmanikm commented on tools/travis.sh
> +                  Invoke-PowerShellGetTest;"
>-PowerShellGetTest [](start = 24, length = 18)

-IsFullTestPass is missing here.

2018-03-27 21:37 UTC, bmanikm commented on PowerShellGet/PowerShellGet.psd1
> +
Please consider removing these empty lines.

2018-03-27 21:38 UTC, bmanikm commented
>  

Please fix the encoding of this file.

---
Refers to: PowerShellGet/PSModule.psm1:58 in 66ddc64. [](commit_id = 66ddc6489941a63700b768208c02e862ab85cfb3, deletion_comment = False)

2018-03-27 21:40 UTC, bmanikm commented on PowerShellGet/private/modulefile/PartOne.ps1
> +Microsoft.PowerShell.Core\Set-StrictMode -Version Latest
Don't we need to add Set-StrictMode in all the .ps1 files under public and private folders?

2018-03-27 21:42 UTC, bmanikm commented on Tests/PSGetPublishScript.Tests.ps1
>      It "InstallScriptWithExistingCommand" {
Please consider reverting this change in this file.

2018-03-27 21:46 UTC, bmanikm commented on tools/build.psm1
> +} #>
Why do we need this change?

2018-03-27 21:57 UTC, bmanikm commented on appveyor.yml
> +        Push-AppveyorArtifact $zipFile
Why can't we retain the existing logic to zip the entire project folder including tests, results and dist, etc.,?

2018-03-28 14:04 UTC, Benny1007 commented on appveyor.yml
> +        Push-AppveyorArtifact $zipFile
What is the purpose of zipping the source?

2018-03-28 14:06 UTC, Benny1007 commented on tools/build.psm1
> +} #>
to extract the module installation from the tests, this logic is moved from the test function. I have a further question though, why does the test function call a get function which actually installs dot net core. That is concerning. A get function should not change state, and especially not install anything.

2018-03-28 14:13 UTC, Benny1007 commented on Tests/PSGetPublishScript.Tests.ps1
>      It "InstallScriptWithExistingCommand" {
Not sure which change you mean (having trouble tracking the comments you are making in this PR)

2018-03-28 21:05 UTC, bmanikm commented on appveyor.yml
> +        Push-AppveyorArtifact $zipFile
Including the source code, tests and test results along with dist folder in the artifact helps us in investigating the test failures when CI runs (PRs, Merge and Daily) are failed. Another option is to create two artifacts, one for dist and other for source & test results.

2018-03-28 21:19 UTC, bmanikm commented on tools/build.psm1
> +} #>
Thanks, please remove the commented code.

2018-03-28 21:22 UTC, bmanikm commented on Tests/PSGetPublishScript.Tests.ps1
>      It "InstallScriptWithExistingCommand" {
The whitespace addition in Tests/PSGetPublishScript.Tests.ps1 file can be removed. Otherwise change history of that file includes this PR even though we are not making any changes.

2018-03-29 00:32 UTC, bmanikm commented on tools/build.psm1
> +function Install-PublishedModule {
PackageManagement needs to be installed prior to installing the PowerShellGet module. This is the reason for the CI test failures. The newly installed module is unable to load as PowerShellGet requires 1.1.7.0 or higher.

Please move the logic starting at line# 191 to #231 in Invoke-PowerShellGetTest function to Install-PublishedModule function.

Starting from `# Install latest PackageManagement from Gallery`

2018-03-29 04:53 UTC, bmanikm commented
@Benny1007 Below are the outstanding comments:
https://github.com/PowerShell/PowerShellGet/pull/242#discussion_r177927072
https://github.com/PowerShell/PowerShellGet/pull/242#discussion_r177890058
https://github.com/PowerShell/PowerShellGet/pull/242#discussion_r177893797
https://github.com/PowerShell/PowerShellGet/pull/242#discussion_r177894453
https://github.com/PowerShell/PowerShellGet/pull/242#discussion_r177581202
https://github.com/PowerShell/PowerShellGet/pull/242#discussion_r177580314

2018-03-30 21:14 UTC, bmanikm commented
@Benny1007 Please let me know if I can submit the required changes to your fork's branch.

2018-03-31 06:27 UTC, Benny1007 commented
@bmanikm sure be my guest, bit busy this weekend ! 👍

2018-04-03 22:44 UTC, bmanikm approved these changes
:shipit:

2018-04-03 22:49 UTC, merged

2018-04-03 22:50 UTC, bmanikm commented
@Benny1007 Thanks a lot for the great contributions to the PowerShellGet repository!

2018-04-03 22:50 UTC, Benny1007 commented
@bmanikm I still have to modify artifact zip to include the source stuff. Also let me know if you'd like me to squish commits before you merge back.

2018-04-03 23:07 UTC, bmanikm commented
@Benny1007 Sorry, I already squashed and merged this PR :(. Could you please submit an another pull request for the artifact zip change?