Alerickson positional path
PowerShell/PowerShellGetv2 pull request #264
Opened 2018-04-18 23:24 UTC by alerickson

added positional parameter to path.

2018-04-18 23:25 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/PowerShell/PowerShellGet?pullRequest=264) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/PowerShell/PowerShellGet?pullRequest=264) before we can accept your contribution.<br/><br/>:x: alerickson [sign now](https://cla.opensource.microsoft.com/PowerShell/PowerShellGet?pullRequest=264)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/PowerShell/PowerShellGet?pullRequest=264) it.</sub>

2018-04-18 23:28 UTC, edyoung requested changes

2018-04-18 23:28 UTC, edyoung commented on PowerShellGet/PowerShellGet.psd1
> +
Obviously this isn't really important, but could you delete these 2 new blank lines and all the other blank lines at the end of this file?

2018-04-18 23:28 UTC, edyoung commented on PowerShellGet/public/psgetfunctions/Save-Module.ps1
> +        [Parameter(Mandatory=$true, Position=1, ParameterSetName='InputOjectAndPathParameterSet')]
Thanks!

2018-04-18 23:37 UTC, alerickson commented on PowerShellGet/PowerShellGet.psd1
> +
Yup, I'll fix that.

2018-04-19 00:29 UTC, edyoung approved these changes

2018-04-19 01:17 UTC, bmanikm commented
@alerickson Thanks for the initial submission! Couple of thoughts:
- If possible, please apply the corresponding change in Save-Script cmdlet as well.
- Consider updating an existing test to specify the path value as positional.

2018-04-19 16:06 UTC, alerickson commented
@bmanikm Thanks!  I'll look into changing the Save-Script cmdlet as well updating tests.

2018-04-19 16:27 UTC, merged