Updated assertion statements in Publish-Module and Publish-Script tests.
PowerShell/PowerShellGetv2 pull request #307
Opened 2018-08-07 17:12 UTC by alerickson

2018-08-07 18:08 UTC, bmanikm commented on Tests/PSGetPublishModule.Tests.ps1
> +            AssertEquals $currentNuGetExeVersion $script:LatestNuGetExeVersion "Current NuGet.exe version is $currentNuGetExeVersion when it should have been $script:LatestNuGetExeVersion."
>AssertEquals $currentNuGetExeVersion $script:LatestNuGetExeVersion [](start = 12, length = 66)

This assertion condition should be `greater than or equal` as NuGet.exe's version gets changed with the new release.

2018-08-07 18:13 UTC, bmanikm commented on Tests/PSGetPublishModule.Tests.ps1
> +            AssertEquals $currentNuGetExeVersion $script:LatestNuGetExeVersion "Current NuGet.exe version is $currentNuGetExeVersion when it should have been $script:LatestNuGetExeVersion."
This is also applicable to all the changed tests in this PR.

---
In reply to: [208331348](https://github.com/PowerShell/PowerShellGet/pull/307#discussion_r208331348) [](ancestors = 208331348)

2018-08-07 18:15 UTC, bmanikm commented on Tests/PSGetPublishModule.Tests.ps1
> +            AssertEquals $currentNuGetExeVersion $script:LatestNuGetExeVersion "Current NuGet.exe version is $currentNuGetExeVersion when it should have been $script:LatestNuGetExeVersion."
Please note that it should be the version comparison, not the string comparison

---
In reply to: [208332906](https://github.com/PowerShell/PowerShellGet/pull/307#discussion_r208332906) [](ancestors = 208332906,208331348)

2018-08-07 18:15 UTC, bmanikm requested changes
:clock1:

2018-08-08 17:17 UTC, bmanikm commented on Tests/PSGetPublishModule.Tests.ps1
> +            Assert (test-path $script:ProgramDataExePath) "NuGet.exe did not install properly.  The file could not be found under path $script:ProgramDataExePath."
>$script:ProgramDataExePath [](start = 135, length = 26)

This is full path of the NuGet.exe, I think it should be $script:PSGetProgramDataPath, right? if yes, please change it here and at other places too. otherwise, consider updating the assertion message

2018-08-08 17:23 UTC, alerickson commented on Tests/PSGetPublishModule.Tests.ps1
> +            Assert (test-path $script:ProgramDataExePath) "NuGet.exe did not install properly.  The file could not be found under path $script:ProgramDataExePath."
Yes you're right,  I'll just change the message from:  
"NuGet.exe did not install properly.  The file could not be found under path $script:ProgramDataExePath." 
to: 
"NuGet.exe did not install properly.  The file could not be found under path $script:PSGetProgramDataPath."

2018-08-08 18:35 UTC, bmanikm approved these changes
:shipit:

2018-08-08 18:37 UTC, merged