Change default scope in Install-Module and Install-Script
PowerShell/PowerShellGetv2 pull request #315
Opened 2018-08-22 21:43 UTC by alerickson

2018-08-22 22:20 UTC, edyoung reviewed
Thanks!

2018-08-22 22:20 UTC, edyoung commented on PowerShellGet/public/psgetfunctions/Install-Module.ps1
> -            $message = $LocalizedData.InstallModuleNeedsCurrentUserScopeParameterForNonAdminUser -f @($script:programFilesModulesPath, $script:MyDocumentsModulesPath)
Consider: when the user is not an admin and they explicitly specify  -Scope AllUsers shouldn't they see this message?

2018-08-22 22:20 UTC, edyoung commented on Tests/PowerShellGet.Tests.ps1
> +    It "Should install a module correctly to the required location with CurrentUser scope and no elevated privileges" {
do these tests always run without elevated privileges, or just with the default privileges of how you start the shell? ie if I run these tests in an Administrator window won't they fail?

2018-08-22 23:10 UTC, alerickson commented on PowerShellGet/public/psgetfunctions/Install-Module.ps1
> -            $message = $LocalizedData.InstallModuleNeedsCurrentUserScopeParameterForNonAdminUser -f @($script:programFilesModulesPath, $script:MyDocumentsModulesPath)
They still see the error message because this function calls PackageManagement\Install-Module, which has the same error message.  I don't think it's necessary to keep it in there unless there's a specific situation where it's advantageous to throw the error early on.

2018-08-22 23:27 UTC, alerickson commented on Tests/PowerShellGet.Tests.ps1
> +    It "Should install a module correctly to the required location with CurrentUser scope and no elevated privileges" {
The tests will run based off of the default privileges of the shell.  The previous install-module/install-script tests were already split up into "Module tests"  and "Module tests (Admin)" (the latter is tagged with "RequireAdminOnWindows").  Running without privileges causes all the non-elevated privilege tests to pass and vice versa.

2018-08-23 02:59 UTC, edyoung commented
Lgtm

2018-08-23 20:28 UTC, bmanikm commented on PowerShellGet/public/psgetfunctions/Install-Module.ps1
> +            if(Test-RunningAsElevated)
>if(Test-RunningAsElevated) [](start = 12, length = 26)

On non-Windows OS platforms, this function returns true as there is no straight forward way to identify whether PS is running as admin. I think, the default scope the non-Windows platforms should be CurrentUser.

2018-08-23 20:32 UTC, bmanikm commented on Tests/PowerShellGet.Tests.ps1
> +        $installedModuleInfo.InstalledLocation.StartsWith($script:MyDocumentsModulesPath, [System.StringComparison]::OrdinalIgnoreCase) | Should Be $true
This tests in this file gets executed only in the daily test pass and it is sanity tests file for PS core builds.
In PowerShellGet daily test runs, all the tests in this file are executed with admin privileges.

2018-08-23 20:34 UTC, bmanikm commented on PowerShellGet/public/psgetfunctions/Install-Module.ps1
> +            $Scope = "CurrentUser"
>$Scope = "CurrentUser" [](start = 12, length = 22)

It is also required to change the default scope value in the Install-Package provider function as users can use the PackageManagement Install-Package cmdlet with PowerShellGet provider name.

2018-08-23 20:34 UTC, bmanikm requested changes
:clock1:

2018-08-24 20:53 UTC, alerickson commented on Tests/PowerShellGet.Tests.ps1
> +        $installedModuleInfo.InstalledLocation.StartsWith($script:MyDocumentsModulesPath, [System.StringComparison]::OrdinalIgnoreCase) | Should Be $true
@bmanikm So what should I do to ensure both admin and non-admin tests run?  Should I only include admin tests?

2018-08-27 18:53 UTC, bmanikm commented on Tests/PowerShellGet.Tests.ps1
> +        $installedModuleInfo.InstalledLocation.StartsWith($script:MyDocumentsModulesPath, [System.StringComparison]::OrdinalIgnoreCase) | Should Be $true
Please take a look at https://github.com/PowerShell/PowerShellGet/blob/development/Tests/PSGetInstallModule.Tests.ps1#L522 for running the tests as non-admin.

2018-09-10 18:08 UTC, alerickson commented
@bmanikm can you review recent changes?  Core tests are temporarily skipped until dotnet in appveyor environment is updated.

2018-09-10 18:36 UTC, bmanikm commented on PowerShellGet/private/functions/Install-PackageUtility.ps1
> +    $script:IsWindowsOS = (-not (Get-Variable -Name IsWindows -ErrorAction Ignore)) -or $IsWindows
>$script:IsWindowsOS = (-not (Get-Variable -Name IsWindows -ErrorAction Ignore)) -or $IsWindows [](start = 4, length = 94)

Any specific reason for not using $script:IsWindows defined in .\PowerShellGet\private\modulefile\PartOne.ps1 ?

2018-09-10 19:10 UTC, alerickson commented on PowerShellGet/private/functions/Install-PackageUtility.ps1
> +    $script:IsWindowsOS = (-not (Get-Variable -Name IsWindows -ErrorAction Ignore)) -or $IsWindows
I made that change, please let me know if there's other changes I should make before pushing.

2018-09-10 19:28 UTC, bmanikm commented on Tests/PSGetInstallModule.Tests.ps1
> +                                                                Register-PSRepository -Name INTGallery -SourceLocation https://dtlgalleryint.cloudapp.net/api/v2/ -InstallationPolicy Trusted
>https://dtlgalleryint.cloudapp.net/api/v2/ [](start = 119, length = 42)

Please use www.poshtestgallery.com here

2018-09-11 16:50 UTC, kilasuit commented on PowerShellGet/public/psgetfunctions/Install-Module.ps1
> +            $Scope = "CurrentUser"
I think that whilst yes you could do that, the majority would not drop down to use Install-Package instead of Install-Module unless really needed, which I can't think of a reason off the top of my head as to why anyone would

2018-09-12 01:12 UTC, alerickson commented
@JKeithB can you review the changelog?  I included scope changes made to "install-package", but it's a provider function so I'm not sure how that should be treated.

2018-09-12 01:29 UTC, JKeithB commented on CHANGELOG.md
> +
I would separate these differently. Suggested rewording accounts for the fact that most users are on PowerShell 5.1:
Default user scope for Install-Module, Install-Script, and Install-Package has changed. For Windows PowerShell (version 5.1), the default user scope is AllUsers when running in an elevated session, and CurrentUser at all other times. 
For  PowerShell version 6.0.0 and above, the default user scope is always CurrentUser.

2018-09-12 17:29 UTC, bmanikm commented on PowerShellGet/public/psgetfunctions/Install-Script.ps1
> +            $message = $LocalizedData.InstallScriptAdminPrivilegeRequiredForAllUsersScope -f @($script:programFilesModulesPath, $script:MyDocumentsModulesPath)
>@($script:programFilesModulesPath, $script:MyDocumentsModulesPath) [](start = 93, length = 66)

These vars are for modules, please use @($script:ProgramFilesScriptsPath, $script:MyDocumentsScriptsPath) here.

2018-09-13 00:06 UTC, alerickson commented
@bmanikm the tests are no longer hanging.  I believe everything should be good to go now.

2018-09-13 00:19 UTC, bmanikm approved these changes

2018-09-13 00:21 UTC, merged