Ss ps get offline
PowerShell/PowerShellGetv2 pull request #354
Opened 2018-11-01 16:13 UTC by SydneyhSmith

Uploading Module for bootstrapping PowerShell Get

2018-11-01 17:23 UTC, bmanikm commented on Utilities/OfflinePowerShellGet/OfflinePowerShellGetDeploy.psd1
> +        # ProjectUri = 'https://github.com/powershell/powershellget/<<NEED TO CREATE>>'
Please add Tags and ProjectUri

2018-11-01 17:25 UTC, bmanikm commented on Utilities/OfflinePowerShellGet/OfflinePowerShellGetSetup.psm1
> +        [string] $NuGetSource = "https://dist.nuget.org/win-x86-commandline/v2.8.6/nuget.exe"
>"https://dist.nuget.org/win-x86-commandline/v2.8.6/nuget.exe" [](start = 32, length = 61)

Use latest version of NuGet.exe --> 
[https://dist.nuget.org/win-x86-commandline/latest/nuget.exe](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) #Closed

2018-11-01 17:29 UTC, bmanikm commented on Utilities/OfflinePowerShellGet/OfflinePowerShellGetSetup.psm1
> +"@ -Destination "$env:ProgramData\Microsoft\Windows\PowerShell\PowerShellGet"
>$env:ProgramData [](start = 17, length = 16)

It looks this module works only on Windows. Consider enabling this on non-Windows platforms. Otherwise, please convey this in the description and also add 'Desktop' as CompatiblePSEditions key value in the .psd1 file.

2018-11-01 17:29 UTC, bmanikm requested changes
:clock1:

2018-11-01 19:06 UTC, edyoung commented on Utilities/OfflinePowerShellGet/OfflinePowerShellGetSetup.psm1
> +"@ -Destination "$env:ProgramData\Microsoft\Windows\PowerShell\PowerShellGet"
I thought for pscore we expect end user to install dotnet?

2018-11-05 20:11 UTC, merged

2018-11-05 20:17 UTC, sdwheeler commented on Utilities/OfflinePowerShellGet/OfflinePowerShellGetDeploy.psd1
> +ModuleVersion = '0.1.0'
Are you going to change the version number? This is the same as the version published to the gallery now.