refactor nuget operations out of utility function
PowerShell/PowerShellGetv2 pull request #444
Opened 2019-03-14 14:45 UTC by Benny1007

2019-03-14 15:52 UTC, edyoung requested changes
Thanks a lot - I think this will definitely be cleaner than current state. Not all of the comments (especially the ones which say 'consider') are mandatory - if you don't think they make sense just resolve them

2019-03-14 15:52 UTC, edyoung commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +        $dotnetCliPath = (Get-Command -Name "dotnet").Source
for symmetry with the nuget.exe case we shouldn't we  check if dotnet was  found?

2019-03-14 15:52 UTC, edyoung commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +
why not remove the tem path here

2019-03-14 15:52 UTC, edyoung commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +    }
PowerShellGallery does not enforce the 4000 character limit and we have modules which exceed it. Probably better to Write-Warning "Tag list exceeded 4000 characters and may not be accepted by some Nuget feeds" without truncating it

2019-03-14 15:52 UTC, edyoung commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +        $dependencyObject = New-Object -TypeName PSCustomObject -Property $props
You could also do $dependencyObject = [PSCustomObject]$props, btw

2019-03-14 15:52 UTC, edyoung commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +    # fix#335 refactor to use new New-NuspecFile function.
I don't think we need the comment, it won't mean anything to a future reader of the code

2019-03-14 15:52 UTC, edyoung commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +        $NuspecFullName = Join-Path -Path $NugetPackageRoot -ChildPath "$Name.nuspec"
You could consider having New-NuspecFile return the path of the file it created? up to you

2019-03-14 15:52 UTC, edyoung commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
>          }
does there need to be an else to cover producing an error when neither nuget or dotnet were found?

2019-03-14 15:52 UTC, edyoung commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +        $NupkgFullName = Join-Path -Path $NugetPackageRoot -ChildPath "$Name.$Version.nupkg"
New-NugetPackage could return name of the package it created

2019-03-14 15:52 UTC, edyoung commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +    # Fix#335 refactor to use new Publish-NugetPackage function.
I'm not seeing Publish-NugetPackage in this PR?

2019-03-14 23:28 UTC, Benny1007 commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +    # Fix#335 refactor to use new Publish-NugetPackage function.
Oh wow yeah, have re-added.

2019-03-14 23:43 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +        $dotnetCliPath = (Get-Command -Name "dotnet").Source
We could do for symmetry I guess, however NugetExePath is fed in as an input, the dotnet cli command is found using Get-Command and indexing into .Source on line 58 would throw an error which would be picked up by the try/catch in line 382 of the calling Publish-PSArtifactUtility function. Personally I prefer this approach and would rather have the nuget.exe case call get-command nuget.exe or something similar but I am not sure of all the ramifications and where else exactly nuget.exe is searched for and found using PowershellGet. Happy to change though unless you can shed any more light on it.

2019-03-15 00:43 UTC, Benny1007 commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
>          }
line 69 should populate these script level variables though with Install-NuGetClientBinaries. Not a fan of that tbh though. If those variables aren't set would you prefer to exit gracefully with an error message? Would Install-NuGetClientBinaries not do that? not looked at that code.

2019-03-15 01:29 UTC, Benny1007 commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +        $NuspecFullName = Join-Path -Path $NugetPackageRoot -ChildPath "$Name.nuspec"
I think i'll leave this if that's ok, I'd rather explicitly check the file exists and have that blow up catching the exception than assign the result to $NuspecFullName then test-path in an if.

2019-03-15 01:41 UTC, Benny1007 commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +        $NuspecFullName = Join-Path -Path $NugetPackageRoot -ChildPath "$Name.nuspec"
actually scratch that i've made that change.

2019-03-15 04:59 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +
ah yep makes sense. done.

2019-03-15 05:00 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +    }
Done.

2019-03-15 05:00 UTC, Benny1007 commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +        $dependencyObject = New-Object -TypeName PSCustomObject -Property $props
not done

2019-03-15 05:00 UTC, Benny1007 commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +    # fix#335 refactor to use new New-NuspecFile function.
done.

2019-03-15 05:29 UTC, edyoung commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +        $dotnetCliPath = (Get-Command -Name "dotnet").Source
OK

2019-03-15 12:08 UTC, Benny1007 commented
Have addressed most feedback. I can't seem to get these tests to even complete locally or on the build servers though. Do you have any tips? - The test suite is pretty scary.

2019-03-15 19:39 UTC, alerickson commented
@Benny1007 check out https://github.com/PowerShell/PowerShellGet#running-tests for running tests locally.  You can also run Invoke-Pester with a particular test file instead of running the entire suite. 
Also be sure to first run "import-module src/PowerShellGet -force" to ensure you have your latest changes before running tests.

2019-03-17 02:40 UTC, Benny1007 commented
> @Benny1007 check out https://github.com/PowerShell/PowerShellGet#running-tests for running tests locally. You can also run Invoke-Pester with a particular test file instead of running the entire suite.
> Also be sure to first run "import-module src/PowerShellGet -force" to ensure you have your latest changes before running tests.

Thanks, so I have run the entire suite locally and everything passes. 
I have also run the entire suite on my macbook with the latest powershell, this seems to have other issues in some other tests related to permissions to temp drive. 

I have no idea why they are not working on the build server, but it's like they never even finish.

2019-03-20 05:29 UTC, edyoung commented
The tests fail because you're calling a function with a mandatory param but not passing a value. Powershell then stops everything and prompts for the user to supply the argument, which isn't so useful on a CI server, then times out waiting. See this snippet from Travis CI log:


cmdlet New-NuspecFile at command pipeline position 1

Supply values for the following parameters:

Id: 


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

2019-03-20 08:40 UTC, Benny1007 commented
Cool thanks. It's concerning none of this was picked up running the test suite locally. So within the calling function, we can't rely on $PSModuleInfo.Name or $PSScriptInfo.Name having a value or do we just need to fix up the test data where it creates these modules/scripts?

2019-03-20 16:48 UTC, Benny1007 commented
Something that has led to false positives during testing is that if I unload PowerShellGet module with:-
`Remove-Module -Name PowerShellGet -Force`
then load it from the code base with 
`Import-Module -Name .\src\PowerShellGet\PowerShellGet.psd1 -Force`
Then break on say line 119 of PSGet.PublishModule.Tests
I then seem to have 2 PowerShellGet modules loaded. I think this is caused by line 1160 in PSGetTestUtils.psm1
This caused the newer PowerShellGet from C:\Program Files\WindowsPowerShell\Modules\PowerShellGet version 2.1.2 to be loaded and used hence forth masking my issues. 
You come across that before?

2019-03-20 17:59 UTC, alerickson commented
@Benny1007 no I haven't.  Are you following option 1 or option 2 when running tests (https://github.com/PowerShell/PowerShellGet#running-tests)?  I've had issues with the env path unintentionally changing and importing the wrong module, so I prefer to follow the latter.

2019-03-20 19:24 UTC, edyoung commented
I always set $env:psmodulepath to pick up the version under development rather than the installed one, that avoids issues like that

2019-03-21 02:49 UTC, Benny1007 commented
As mentioned in the PR feedback truncating of the Tags has been removed and replace with a warning which won't exactly help #344 but will provided a clearer reason why the publish has failed?

2019-03-21 12:31 UTC, awickham10 commented
> As mentioned in the PR feedback truncating of the Tags has been removed and replace with a warning which won't exactly help #344 but will provided a clearer reason why the publish has failed?

It seems like the problem is Publish-Module includes every function as a tag. What if a switch was added to exclude functions as tags? Something like... `Publish-Module -Name 'MyModule' -ExcludeFunctionsAsTags` that way the odds of hitting the 4000 character limit is drastically reduced?

2019-03-22 05:04 UTC, edyoung approved these changes

2019-03-22 05:06 UTC, edyoung commented
@awickham10 I'd be fine with that (or a -EnforceMaximumTagLength option maybe), but I'd rather keep that a separate change so this is a pure refactor

2019-03-22 05:06 UTC, edyoung commented
Thanks @Benny1007 !

2019-03-22 05:08 UTC, merged

2019-03-22 17:25 UTC, alerickson commented
The Visual Studio 2017, PowerShell Core environment on AppVeyor says it's passing but didn't actually run.  See: https://ci.appveyor.com/project/PowerShell/powershellget/builds/23226384/job/hu9xotrcnsvkyb8a

2019-03-23 10:20 UTC, Benny1007 commented
That's not very good. The build server reports success on a failure?
Looks like the build server didn't have PowerShell core (pwsh.exe) installed?

2019-03-26 15:19 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +        $dotnetCliPath = (Get-Command -Name "dotnet").Source
@Benny1007 @edyoung I would like a Verbose Preference to enable logging which Get-Command is retrieved.  What do you think?

2019-03-26 15:26 UTC, jzabroski commented
@edyoung @Benny1007  I just saw this commit - for some reason it showed up in my GitHub Read folder instead of notifications.  I only reviewed one file so far, though.

2019-03-26 15:30 UTC, jzabroski reviewed
@alerickson  Are you saying @Benny1007  broke the build, or someone in charge of the Appveyor commands wrote a bad pipeline?  Or just "this is broke, I hope someone fixes it"?

2019-03-26 15:30 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +        #perform dotnet pack using a temporary project file.
@edyoung  @Benny1007  Extract this into it's own function.  Replace the comment with a function name.  Use a PowerShell approved verb.

2019-03-26 15:30 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +        $dotnetCliPath = (Get-Command -Name "dotnet").Source
Create Verbose Preference to log which Get-Command is retrieved.  This would be useful in submitting bug reports.  It could even verbose the version of the exe found.

2019-03-26 15:30 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +            throw "dotnet cli failed to pack $stdOut"
This still does not allow inspecting the temporary created project file.  This makes it a bit magical when trying to understand what got uploaded to a repository as part of the publish process.

@Benny1007 @edyoung

2019-03-26 17:51 UTC, alerickson commented
@jzabroski just meant that the PR shouldn't have been merged because the tests for core didn't run.

2019-03-26 23:29 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +        Write-Warning -Message "Nuspec 'Tag' list exceeded max 4000 characters and was truncated."
This appears to address https://github.com/PowerShell/PowerShellGet/issues/344

Additionally, now that this is a first-class function exposable to end-users, the additional request to make 4000 limit configurable for users who want to upload packages to their own nuget server is possible

2019-03-26 23:29 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +    #truncate tags if they exceed nuspec specifications for size.
If you're destructively messing with parameters, create a Process block attached to the params block.

2019-03-26 23:29 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +        $Tags = $Tags.Substring(0, $Tags.LastIndexOf(" "))
This is not guaranteed to truncate at the lesser of 4,000 characters or "full list of tags separated by spaces up to 4,000 characters"

2019-03-26 23:29 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +    }
@Benny1007  The message should be updated to say you're not truncating it.

2019-03-26 23:30 UTC, jzabroski commented on src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1
> +        $dependencyObject = New-Object -TypeName PSCustomObject -Property $props
I think the style @Benny1007  wrote here is more readable.

2019-03-27 01:24 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +        #perform dotnet pack using a temporary project file.
what are the benefits of abstracting this further. Don't want to get into similar situation of Register-PSRepository and Resolve-Location, Get-LocationString, Get-EscapedString etc... This function has a single responsibility - to create a nuget package, having all the code at hand in one file to perform that was the reason for abstracting it in the first place. Personally not a fan of splitting out to multiple functions for the sake of it.

2019-03-27 01:26 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +            throw "dotnet cli failed to pack $stdOut"
Overwrite the outputpath variable and then you would know where the artifact resides.

2019-03-27 01:27 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +    #truncate tags if they exceed nuspec specifications for size.
can you explain this further?

2019-03-27 01:28 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +        Write-Warning -Message "Nuspec 'Tag' list exceeded max 4000 characters and was truncated."
These nuget functions are still private functions and not exposed in the module to the public.

2019-03-27 11:58 UTC, jzabroski commented
How am I supposed to overwrite the output path on a private function?

On Tue, Mar 26, 2019, 9:28 PM benny1007 <notifications@github.com> wrote:

> *@Benny1007* commented on this pull request.
> ------------------------------
>
> In src/PowerShellGet/private/functions/New-NuspecFile.ps1
> <https://github.com/PowerShell/PowerShellGet/pull/444#discussion_r269376643>
> :
>
> > +    $nameSpaceUri = "http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd"
> +    [xml]$xml = New-Object System.Xml.XmlDocument
> +
> +    $xmlDeclaration = $xml.CreateXmlDeclaration("1.0", "utf-8", $null)
> +    $xml.AppendChild($xmlDeclaration) | Out-Null
> +
> +    #create top-level elements
> +    $packageElement = $xml.CreateElement("package", $nameSpaceUri)
> +    $metaDataElement = $xml.CreateElement("metadata", $nameSpaceUri)
> +
> +    #truncate tags if they exceed nuspec specifications for size.
> +    $Tags = $Tags -Join " "
> +
> +    if ($Tags.Length -gt 4000) {
> +        $Tags = $Tags.Substring(0, $Tags.LastIndexOf(" "))
> +        Write-Warning -Message "Nuspec 'Tag' list exceeded max 4000 characters and was truncated."
>
> These nuget functions are still private functions and not exposed in the
> module to the public.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PowerShell/PowerShellGet/pull/444#discussion_r269376643>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAbT_Z0fGzjHdBtWmI7H9mTMHCgf4wAaks5vaskmgaJpZM4b0VCL>
> .
>

2019-03-27 12:01 UTC, jzabroski commented
What's the benefit of having nuget.exe instead of nugetupdate.exe,
nugetpublish.exe, nugethelp.exe? Reductio ad absurdum.

If you think my suggestion makes the code less readable, that's OK. But I
actually think it would improve readability since all you really care about
is "do something, aggregate stdout, srderr and exit code, and return." I
think the fact it's already not handled consistently across the code base
is reason enough to add a helper. Call it Helper/Invoke-Process so that
it's clearer its a cross cutting concept. At the end of the day you should
not care about the ceremony of Process start, redirection and exit codes.



On Tue, Mar 26, 2019, 9:24 PM benny1007 <notifications@github.com> wrote:

> *@Benny1007* commented on this pull request.
> ------------------------------
>
> In src/PowerShellGet/private/functions/New-NugetPackage.ps1
> <https://github.com/PowerShell/PowerShellGet/pull/444#discussion_r269376094>
> :
>
> > +        $processStartInfo.UseShellExecute = $false
> +        $processStartInfo.Arguments = $ArgumentList
> +
> +        $process = New-Object System.Diagnostics.Process
> +        $process.StartInfo = $processStartInfo
> +        $process.Start() | Out-Null
> +        $process.WaitForExit()
> +
> +        if (-Not ($process.ExitCode -eq 0 )) {
> +            $stdErr = $process.StandardError.ReadToEnd()
> +            throw "nuget.exe failed to pack $stdErr"
> +        }
> +    }
> +
> +    if ($PSCmdlet.ParameterSetName -eq "UseDotnetCli") {
> +        #perform dotnet pack using a temporary project file.
>
> what are the benefits of abstracting this further. Don't want to get into
> similar situation of Register-PSRepository and Resolve-Location,
> Get-LocationString, Get-EscapedString etc... This function has a single
> responsibility - to create a nuget package, having all the code at hand in
> one file to perform that was the reason for abstracting it in the first
> place. Personally not a fan of splitting out to multiple functions for the
> sake of it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PowerShell/PowerShellGet/pull/444#discussion_r269376094>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAbT_eyRx9X1Qi9IScNxQC6vfG2oP5tYks5vashagaJpZM4b0VCL>
> .
>

2019-03-29 15:13 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +    #truncate tags if they exceed nuspec specifications for size.
In PowerShell v1, the only way to validate parameters was in a Process block and to throw an exception.  In PowerShell v2, you can use ValidateScript.

2019-03-29 15:14 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +        $Tags = $Tags.Substring(0, $Tags.LastIndexOf(" "))
@Benny1007  Here is a C# way to do what I'm describing. The author is kind enough to post sample data that you can use to test against.  I also recommend making this a private helper function for readability: https://codereview.stackexchange.com/a/163788/193241

2019-03-29 15:15 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +        Write-Warning -Message "Nuspec 'Tag' list exceeded max 4000 characters and was truncated."
Then how am I supposed to follow your advice to overwrite the output path?   See your comment here https://github.com/PowerShell/PowerShellGet/pull/444#discussion_r269376413 - maybe I'm missing something obvious and I apologize for being stubborn if that's the case.

2019-03-29 15:18 UTC, jzabroski commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +        #perform dotnet pack using a temporary project file.
It's not for the sake of it.  It's for building reusable abstractions.  Why is it out fault that the Process API is not designed for consuming a quick task's exit code and standard output and error streams?  We just wrap that and clearly express we care about those 3 things.  See my comment here which when I replied by email 2 days ago somehow got stuck at the bottom of the review: https://github.com/PowerShell/PowerShellGet/pull/444#issuecomment-477119239

2019-03-29 15:22 UTC, jzabroski commented
> @awickham10 I'd be fine with that (or a -EnforceMaximumTagLength option maybe), but I'd rather keep that a separate change so this is a pure refactor

This is a private function right now so it doesn't add a lot of value for something that will never have code coverage in production usage.  The more important question is whether some of these helper functions should be public instead of private.  My gut feeling is that they should be split out into a separate helper module, so that if people want to debug PowerShellGet internals, they can.  This is not a traditional way of thinking about using modules, but it just "Feels right" to me.  Also, by making it a separate module instead of public interface to a major mainstream package, it allows for easier user story to sunset the module once PowerShellGet becomes more stable over time and the need for these utility functions goes away from the public eye.

2019-03-30 00:06 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +        $Tags = $Tags.Substring(0, $Tags.LastIndexOf(" "))
The snippet is outdated, it was recommended in the PR feedback to NOT truncate.

2019-03-30 00:09 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +        Write-Warning -Message "Nuspec 'Tag' list exceeded max 4000 characters and was truncated."
There would have to be another separate PR that exposed the outputpath via the public members. This small refactor was just the start of the re-write of Publish-Module I assume the refactoring for this module will be across Publish-PSArtifactUtility (potentially going away) and Publish-Module.

2019-03-30 00:10 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NugetPackage.ps1
> +            throw "dotnet cli failed to pack $stdOut"
sorry, was missing a question mark off the last comment! would need to pass this through from the public function.

2019-03-30 00:14 UTC, Benny1007 commented on src/PowerShellGet/private/functions/New-NuspecFile.ps1
> +    #truncate tags if they exceed nuspec specifications for size.
I think this comment was in reference to the truncation of tags?, which is now NOT happening but I seem to have left the comment in the code.